language: cpp
compiler: gcc

branches:
    only:
    - travisBranch

before_install:
    - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu wily main universe"
#- sudo apt-get upgrade
    - sudo apt-get update qq
    - sudo apt-get install z3
    - sudo apt-get install libboost-all-dev
    
install: 
    - cd synthesis/libcpp
    - bjam
