language: cpp

matrix:
  include:
    - name: "linux-gcc"
      os: linux
      dist: xenial
      compiler: gcc
    - name: "linux-clang"
      os: linux
      dist: xenial
      compiler: clang
    - name: "osx-gcc"
      os: osx
      compiler: gcc
    - name: "osx-clang"
      os: osx
      compiler: clang

sudo: required

branches:
  only:
    - master
    - travis

git:
  submodules: false

before_install:
  - gem install coveralls-lcov
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install bison ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/bison/bin:$PATH" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export LDFLAGS="-L/usr/local/opt/bison/lib" ; fi

addons:
  apt:
    update: true
    packages:
      - lcov
      - flex
      - bison
      - libboost-all-dev
  homebrew:
    update: true
    packages:
      - flex
      - boost
      - boost-python

install: 
  - export PARENT_DIR=$TRAVIS_BUILD_DIR/../
  # z3 
  - cd $PARENT_DIR
  - git clone https://github.com/Z3Prover/z3.git
  - cd z3
  - git checkout tags/z3-4.7.1 -b v471
  - export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH
  - python scripts/mk_make.py
  - if [[ "$TRAVIS_COMPILER" == "gcc" ]]; then python scripts/mk_make.py ; fi
  - if [[ "$TRAVIS_COMPILER" == "clang" ]]; then export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH ; fi
  - if [[ "$TRAVIS_COMPILER" == "clang" ]]; then CXX=clang++ CC=clang python scripts/mk_make.py ; fi
  - cd build
  - make && sudo make install
  - z3 --version

before_script:
  - chmod ugo+x $TRAVIS_BUILD_DIR/scripts/clean-coverage.sh
  - chmod ugo+x $TRAVIS_BUILD_DIR/scripts/submit-coverage.sh
  - mkdir -p $TRAVIS_BUILD_DIR/build
  - if [[ "$TRAVIS_JOB_NAME" == "linux-gcc" ]]; then source $TRAVIS_BUILD_DIR/scripts/clean-coverage.sh $TRAVIS_BUILD_DIR/build ; fi

script:
  - cd $TRAVIS_BUILD_DIR/build
  - cmake .. -DILANG_BUILD_COV=ON -DCMAKE_BUILD_TYPE=Debug
  - make 
  - sudo make install
  - make run_test
  - ctest -R ExampleCMakeBuild

after_success:
  - if [[ "$TRAVIS_JOB_NAME" == "linux-gcc" ]]; then source $TRAVIS_BUILD_DIR/scripts/submit-coverage.sh $TRAVIS_BUILD_DIR/build ; fi

notifications:
    email: false

