branches:
  only:
    - master
    - travis

git:
  depth: 1
  submodules: false

sudo: required

language: cpp

matrix:
  include:
    - name: "linux-gcc"
      os: linux
      dist: xenial
      compiler: gcc
      before_install:
        - gem install coveralls-lcov
      before_script:
        - mkdir -p $TRAVIS_BUILD_DIR/build 
        - source $TRAVIS_BUILD_DIR/scripts/clean-coverage.sh $TRAVIS_BUILD_DIR/build
      after_success:
        - source $TRAVIS_BUILD_DIR/scripts/submit-coverage.sh $TRAVIS_BUILD_DIR/build

    - name: "linux-clang"
      os: linux
      dist: xenial
      compiler: clang

    - name: "gcc49"
      os: linux
      dist: xenial
      addons:
        apt: 
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - flex
            - bison
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
      before_install:
        - eval "${MATRIX_EVAL}"

    - name: "osx"
      os: osx
      before_install:
        - brew install bison
        - export PATH="/usr/local/opt/bison/bin:$PATH"
        - export LDFLAGS="-L/usr/local/opt/bison/lib"

addons:
  apt:
    update: true
    packages:
      - lcov
      - flex
      - bison
      - libboost-all-dev
  homebrew:
    update: true
    packages:
      - flex
      - python
      - boost
      - boost-python

cache:
  directories:
    - $HOME/_cache

install: 
  - mkdir -p $HOME/_cache
  - export Z3_CACHED="$(find $HOME/_cache/ -name z3 | grep -c "z3")"
  - cd $HOME/_cache
  - if [[ "$Z3_CACHED" == "0" ]] ; then git clone https://github.com/Z3Prover/z3.git ; fi
  - cd z3
  - if [[ "$Z3_CACHED" == "0" ]] ; then git checkout tags/z3-4.8.4 -b v484 ; fi
  - if [[ "$Z3_CACHED" == "0" ]] ; then python scripts/mk_make.py ; fi
  - if [[ "$Z3_CACHED" == "0" && "$TRAVIS_COMPILER" == "clang" ]] ; then export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH ; fi
  - if [[ "$Z3_CACHED" == "0" && "$TRAVIS_COMPILER" == "clang" ]] ; then CXX=clang++ CC=clang python scripts/mk_make.py ; fi
  - cd build
  - if [[ "$Z3_CACHED" == "0" ]] ; then make -j$(nproc) ; fi
  - sudo make install
  - which z3
  - z3 --version

script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir -p build
  - cd build
  - cmake .. -DILANG_BUILD_COV=ON -DCMAKE_BUILD_TYPE=Debug
  - make -j$(nproc)
  - sudo make install
  - make run_test
  - ctest -R ExampleCMakeBuild

notifications:
    email: false
