language: cpp
os: linux
sudo: required
dist: trusty
compiler:
  - g++
  #- clang++

branches:
  only:
    - master
    - coverity_check
    - coveralls
    - travis

git:
  depth: 1

env:
  global:
    - secure: "V5nOxUXoHE4eVS6f1byDFNKrQQh1LrLDjukZ5FEBOfto+by+cZxrk0/KUG++CHFv2P7ePhTqcT+GHAjeGEfEkwirZFcjd6R7b/3d86zSTSTsh16o99IYeJ3rvH41fSr4Se9Lx2eeEOZmGOxdyNJykh8xGZRSPvpR/1GnJYL6owIEhOJzBx9vGVqJ9ePItbIw6/IcuvYYt9GnoS3tlnxSMeXnkCjoy2OVwNuckkPWfOKOLL6GgJynNdwPPlx1dHs3XjKB0eMA0wl90kmYKCIkRsRjXDPISiVCvjVGQm0YtqALO+3uLwQxG12c3DL8USpQgiuwjIENFi4rKZgmZt3YqmfQpoHrfeEV7Mf3kaUvSpJTEaIT563a6cQzU7fGoONSlLeYKQZqsmZtPdAlJ1KszwaL8ufcp0YOktcZ3Ra1DjFRkpWDTUJTGZCgicE8btywS7ADdyyRnVGnoYiXOZ+A4zNDSaYyXUYE4ZR7y9GUQ0e8jfeMHboIYufGd610pYBAaQCdZd8YBUFOAsAzLgYfiUphIrKSif5R/3JUdz8OClsm7983MY/kjiRVDfjdKQm5cZ8t8OlvRVpRsaN169A4mXpAMOx+ycnakzkG6RD6gWKPI+NPnZhZCrKoUS1qD287xXPoYMmg2PUVzRkHRrG9U/PdwrrmVdq0jZ58K0VtMhQ="

addons:
  coverity_scan:
    project:
      name: "Bo-Yuan-Huang/ILA-Tools"
      description: "ILA build submitted via Travis CI"
    notification_email: byhuang1992@gmail.com
    build_command_prepend: "cmake -Dcoverage=ON -DZ3_INCLUDE_DIR=/usr/include $TRAVIS_BUILD_DIR"
    build_command: "make"
    branch_pattern: coverity_check

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq --yes update

install: 
  - gem install coveralls-lcov
  - sudo apt-get install --yes cmake cmake-data
  - sudo apt-get install --yes libboost-all-dev
  - sudo apt-get install --yes lcov

before_script:
  - export PARENT_DIR=$TRAVIS_BUILD_DIR/../
  # z3
  - cd $PARENT_DIR
  - git clone --depth 1 https://github.com/Z3Prover/z3.git
  - cd z3
  - python scripts/mk_make.py
  - cd build
  - make; sudo make install
  # glog
  - cd $PARENT_DIR
  - git clone --depth 1 https://github.com/google/glog.git
  - mkdir -p $PARENT_DIR/glog/build/
  - cd $PARENT_DIR/glog/build/ 
  - cmake ..
  - make && sudo make install
  # coverage test
  - lcov --version
  - gcov --version
  - g++ --version
  # create Makefile
  - mkdir -p $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build
  - lcov --directory $TRAVIS_BUILD_DIR/build --zerocounters

script:
  - cd $TRAVIS_BUILD_DIR/build
  - cmake -L -DZ3_INCLUDE_DIR=/usr/include -Dglog_DIR=$PARENT_DIR/glog/build -Dcoverage=ON -Dpython_api=ON -Ddebug=ON $TRAVIS_BUILD_DIR
  - make

after_success:
  - make run_test
  - lcov --directory $TRAVIS_BUILD_DIR/build --capture --output-file coverage.info 
  - lcov --remove coverage.info 'glog/*' 'test/*' 'app/*' 'cmake/*' '/usr/*' --output-file coverage.info 
  - lcov --list coverage.info 
  - coveralls-lcov coverage.info 

notifications:
    email: false
