language: cpp
os: linux
sudo: required
dist: trusty

branches:
  only:
    - master
    - coverity_check

git:
  depth: 1

#env:
#  global:
#    - secure: ""

addons:
  coverity_scan:
    project:
      name: "Bo-Yuan-Huang/ILA"
      description: "ILA build submitted via Travis CI"
    notification_email: byhuang1992@gmail.com
    build_command_prepend: "cmake -Dcoverage=ON -DZ3_INCLUDE_DIR=/usr/include $PARENT_DIR"
    build_command: "make"
    branch_pattern: coverity_scan

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - sudo apt-get update -qq yes

install: 
  - gem install coveralls-lcov
  - sudo apt-get install --yes cmake cmake-data
  - sudo apt-get install --yes libboost-dev
  - sudo apt-get install --yes lcov

before_script:
  - PARENT_DIR=$(pwd)
  # z3
  - git clone --depth 1 https://github.com/Z3Prover/z3.git
  - cd z3
  - python scripts/mk_make.py
  - cd build
  - make; sudo make install
  - cd $PARENT_DIR
  # coverage test
  - lcov --version
  - gcov --version
  - g++ --version
  # create Makefile
  - mkdir -p $PARENT_DIR/build && cd $PARENT_DIR/build
  - lcov --directory $PARENT_DIR/build --zerocounters

script:
  - cd $PARENT_DIR/build
  - cmake -L -DZ3_INCLUDE_DIR=/usr/include -Dcoverage=ON $PARENT_DIR
  - make

after_success:
  - make gtest
  - lcov --directory $PARENTDIR/build --capture --output-file coverage.info 
  - lcov --remove coverage.info 'test/*' 'app/*' 'external/*' 'cmake/*' '/usr/*' --output-file coverage.info 
  - lcov --list coverage.info 
  - coveralls-lcov coverage.info 

notifications:
    email: false
