version: 1.0.{build}
image:
- Ubuntu1804
clone_depth: 1
build_script:
- sh: >-
    sudo apt update

    sudo DEBIAN_FRONTEND=noninteractive apt install --yes bison libboost-all-dev

    sudo apt install --yes flex


    # z3

    cd $HOME

    git clone https://github.com/Z3Prover/z3.git

    cd z3

    python scripts/mk_make.py

    cd build

    make -j$(nproc)

    sudo make install


    # ILAng

    cd $APPVEYOR_BUILD_FOLDER

    mkdir -p build

    cd build

    cmake ..

    make -j$(nproc)

    sudo make install

    make test

