trigger:
- master

pr:
- master

# File: azure-pipelines.yml

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: |
      brew update
      brew install bison
      brew install boost
      brew install boost-python
      brew install z3
    displayName: 'package'
  - script: |
      export PATH="/usr/local/opt/bison/bin:$PATH"
      export LDFLAGS="-L/usr/local/opt/bison/lib"
      mkdir -p build && cd build
      cmake ..
      make
      sudo make install
      make test
    displayName: 'build'

- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      sudo apt-get update
      sudo apt-get install bison
      sudo apt-get install flex
      sudo apt-get install libboost-all-dev
      sudo apt-get install z3
      sudo apt-get install libz3-dev
    displayName: 'package'
  - script: |
      mkdir -p build && cd build
      cmake .. 
      make 
      sudo make install
      make test
    displayName: 'build'

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      choco install winflexbison3
      choco install wget
    displayName: 'package'
  - script: |
      wget https://github.com/Z3Prover/z3/releases/download/Z3-4.8.5/z3-4.8.5-x64-win.zip
      unzip z3-4.8.5-x64-win.zip
    displayName: 'z3'
  - script: |
      git clone https://github.com/Bo-Yuan-Huang/verilog-parser.git 
      cd verilog-parser
      md build
      cd build
      cmake ..
      cmake --build .
      cmake --build . --target install
    displayName: 'Verilog-parser'
  - script: |
      mkdir -p build && cd build
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
      cmake .. -DILANG_BUILD_SYNTH=OFF -DILANG_FETCH_DEPS=OFF -DZ3_INCLUDE_DIR="..\z3-4.8.5-x64-win\include" -DZ3_LIBRARY="..\z3-4.8.5-x64-win\bin\libz3.lib" -DZ3_EXEC="..\z3-4.8.5-x64-win\bin\z3.exe"
      cmake --build .
      cmake --build . --target install
      cmake --build . --target test
    displayName: 'build'

